import React from 'react';
import { 
  Home, 
  Search, 
  GitBranch, 
  Settings, 
  MessageSquare, 
  FileText,
  Code, 
  User, 
  Briefcase, 
  GraduationCap, 
  Mail, 
  Globe, 
  Rss, 
  Terminal as TerminalIcon, 
  MessageCircle as ChatIcon,
  Zap,
  Award,
  Users,
  BookOpen,
  Send,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  Plus,
  Trash2,
  Edit2,
  Copy,
  CheckCircle,
  AlertCircle,
  Info,
  HelpCircle,
  Folder,
  FolderOpen,
  File,
  Download,
  Upload,
  ExternalLink,
  Link as LinkIcon,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Star,
  Heart,
  Share2,
  MoreHorizontal,
  MoreVertical,
  Minimize2,
  Maximize2,
  Loader,
  RefreshCw,
  Trash,
  GitCommit,
  GitPullRequest,
  GitMerge
} from 'lucide-react';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: string;
}

const iconMap: { [key: string]: React.ElementType } = {
  home: Home,
  search: Search,
  'git-branch': GitBranch,
  settings: Settings,
  'message-square': MessageSquare,
  'file-text': FileText,
  files: FileText,
  code: Code,
  user: User,
  briefcase: Briefcase,
  'graduation-cap': GraduationCap,
  mail: Mail,
  globe: Globe,
  rss: Rss,
  terminal: TerminalIcon,
  comment: ChatIcon,
  zap: Zap,
  award: Award,
  users: Users,
  'book-open': BookOpen,
  send: Send,
  menu: Menu,
  x: X,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  plus: Plus,
  trash2: Trash2,
  trash: Trash,
  edit: Edit2,
  'edit2': Edit2,
  copy: Copy,
  check: CheckCircle,
  'check-circle': CheckCircle,
  'alert-circle': AlertCircle,
  info: Info,
  'help-circle': HelpCircle,
  folder: Folder,
  'folder-open': FolderOpen,
  file: File,
  download: Download,
  upload: Upload,
  'external-link': ExternalLink,
  link: LinkIcon,
  eye: Eye,
  'eye-off': EyeOff,
  lock: Lock,
  unlock: Unlock,
  star: Star,
  heart: Heart,
  'share-2': Share2,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  minimize2: Minimize2,
  maximize2: Maximize2,
  loader: Loader,
  'refresh-cw': RefreshCw,
  'git-commit': GitCommit,
  'git-pull-request': GitPullRequest,
  'git-merge': GitMerge,
};

export const Icon: React.FC<IconProps> = ({ name, ...props }) => {
  const LucideIcon = iconMap[name];
  if (!LucideIcon) {
    console.warn(`Icon with name "${name}" not found.`);
    return null;
  }
  return <LucideIcon {...props} />;
};
